### ISSUE TITLE
Expand Filtering

### ISSUE THREAD

**Issue by florin103** [BlaiseD/LogicBuilder.OData#1]
Hi, This library is very helpful.
Guys, do you intend to keep this growing?
I need an example of how to filter over the expanded property. 
ex:
http://localhost:48117/shares/9312/?$filter=Status eq 'Live'&$expand=Prices($orderby=Date desc;$top=1;$select=Date, PricePerUnit, ChangeValue, UnswungPrice)
Could this be achieved?
I see there is a Method GetSelects() which is not used. How could we hook that method into Automapper so that the objects returned by the query will only contain that fields of the resulting model.

**Comment by BlaiseD** [comment]
I considered `GetSelects()` to return a subset of fields but I think when you define a method such as `public IActionResult Get(ODataQueryOptions<CoreBuilding> options)` on the controller, OData expects a CoreBuilding object back and will handle the select.

If my memory is correct then it throws an exception for an anonymous type returned from a lambda selector.  I don't see a **Status** field in your example so your question isn't quite clear.  I would have thought it was [possible](https://stackoverflow.com/questions/18341764/odata-v2-filter-by-property-of-expanded-entity). Maybe create a sample repository or a gist or sample using objects in this repo.

**Comment by florin103** [comment]
Hi. Where would you call the getSelects method in your example to return the anonymous type?
The filtering in my example on the child entity is done by the top=1. And there is no treatment of these options for the BuildIncludes() Could you help? Thank you. Most appreciated anyway. 
Using Odata and Automapper in same project is nightmare.

**Comment by florin103** [comment]
I modified the code to use ProjectTo() at the end. Instead of Map.

**Comment by florin103** [comment]
I would expect Automaper to know what members I need from the resulting model and not project them on the IQueryable. Is it possible?

**Comment by florin103** [comment]
Or for the members I don't need to set default values so the db would not have to return them

**Comment by BlaiseD** [comment]
First add a sample OData project [here](https://github.com/florin103?tab=repositories) with your classes.  Include the query string and expected results.  Then I can help.

**Comment by florin103** [comment]
Hi Blaise,
To simplify this a little bit I think we can use your example code.
Lets say we want:
"http://localhost:<port\>/opstenant?$select=Name"
This should return the all the Tenants but we are interested only in Name of the Tenant.
The code I changed in QueryableExtension.cs looks like this:

       public static ICollection<TModel> Get<TModel, TData>(this IQueryable<TData> query, IMapper mapper,
            Expression<Func<TModel, bool>> filter = null,
            Expression<Func<IQueryable<TModel>, IQueryable<TModel>>> queryFunc = null,
            IEnumerable<Expression<Func<TModel, object>>> includeProperties = null)
        {
            //Map the expressions
            Expression<Func<TData, bool>> f = mapper.MapExpression<Expression<Func<TData, bool>>>(filter);
            Func<IQueryable<TData>, IQueryable<TData>> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, IQueryable<TData>>>>(queryFunc)?.Compile();
            ICollection<Expression<Func<TData, object>>> includes = mapper.MapIncludesList<Expression<Func<TData, object>>>(includeProperties);

            if (filter != null)
                query = query.Where(f);

            if (includes != null)
                query = includes.Aggregate(query, (q, next) => q.Include(next));

            if (mappedQueryFunc != null)
                query = mappedQueryFunc(query);

            var result = query.ProjectTo<TModel>();// includeProperties.ToArray());

            //Call the store
            //IQueryable<TData> result = mappedQueryFunc != null ? mappedQueryFunc(query) : query;

            // var tt = mapper.Map<IQueryable<TData>, IQueryable<TModel>>(result);//.ToList();
            return result.ToList();
        }
What I need is to have the SQL generated by 'result' IQueryable, query only for the Name of the tenants.

**Comment by BlaiseD** [comment]
I'm saying if you simply call `http://localhost:<port>/opstenant?$select=Name` with no code changes OData does the select for you.  You should see the following in the browser:
```json
{"@odata.context":"http://localhost:18664/$metadata#OpsTenant(Name)","value":[{"Name":"One"},{"Name":"Two"}]}
```
Does that work?

**Comment by BlaiseD** [comment]
If you need the SQL query to be more narrow then yes the `GetSelects()` would be the way to go.  But you'll have research how to call `public IActionResult Get(ODataQueryOptions<CoreBuilding> options)`  without throwing an exception:

Try:
```c#
        public IActionResult Get(ODataQueryOptions<OpsTenant> options)
        {
            return Ok(Repository.MandatorSet.Select(m => new { Name = m.Name }));
        }
```
with
```
http://localhost:<port>/opstenant?$select=Name
```

And it blows up.  On the other hand http://localhost:16324/opstenant without the $select works on the same method.

I don't have a solution yet.

**Comment by BlaiseD** [comment]
ok - now I'm understanding.  I think if **Name** is the only field in TModel then `ProjectTo()` solves that problem for you.  Is that what you're saying?  Just create a PR.  That took me a while.

**Comment by florin103** [comment]
Thanks Blaise. 
The TModel is in our example is the one that you have specified in your sources: 
    public class OpsTenant
    {
        [Key]
        public Guid Identity { get; set; }
        public string Name { get; set; }
        public ICollection<CoreBuilding> Buildings { get; set; }
    }
I should not request Identity from DB.
What I could think of is to have a way of modifying the mapping between TData to TModel, before ProjectTo() call so that for the Identity member would tell automapper to ignore it. This way it will project the IQueryable<TData\> to IQueryable<TModel\> but without requiring the Identity field.
I could use the GetSelects() method to get the list of required fields: only the Name as per my example.
And I wish I could use this list to modify the map at runtime to ignore the Identity field from mapping.

Could one change the mapping at runtime? Before ProjectTo() and also be threadsafe?

I see a possibility of achieving this in IMapper.Map() call but I couldn't make it work yet. Smth like this:

   var yyuu = mapper.Map<IQueryable<TData>, IEnumerable<TModel>>(result, t =>
             {             
                 t.ConfigureMap().ForMember("Identity", hy => hy.Ignore()) ;
             }).ToList();
It crashes saying there is no Identity field:
{"Cannot find member Identity of type System.Collections.Generic.IEnumerable`1[OpsTenant].\r\nParameter name: name"}

**Comment by BlaiseD** [comment]
You're saying 
```c#
            CreateMap<TMandator, OpsTenant>()
                //.ForMember(d => d.Identity, o => o.MapFrom(s => s.Identity))
                .ForMember(d => d.Name, o => o.MapFrom(s => s.Name))
                //.ForMember(d => d.Buildings, o => { o.MapFrom(s => s.Buildings); o.ExplicitExpansion(); })
                .ForAllOtherMembers(o => o.Ignore());
```
gets you the result you need but you want to do it dynamically?

Your error message gives you a clue `mapper.Map<IQueryable, IEnumerable>` .  Identity is a member of OpsTenant not IEnumerable. 

Other wise Dynamic mapping is a question for the AutoMapper repository.  Warning: they might tell you to ask StackOverflow if it isn't a bug.

Also note that **Ignore** will not prevent default values for literal types from being serialized. i.e. you could get this type of result.

```javascript
{"@odata.context":"http://localhost:18664/$metadata#OpsTenant","value":[{"Identity":"00000000-0000-0000-0000-000000000000","Name":"One"},{"Identity":"00000000-0000-0000-0000-000000000000","Name":"Two"}]}
```

**Comment by BlaiseD** [comment]
It is possible to do something like the following:
```c#
        public static ICollection<TModel> Get<TModel, TData>(this IQueryable<TData> query, IMapper mapper, ODataQueryOptions<TModel> options)
            where TModel : class
        {
            List<string> selects = options.SelectExpand.GetSelects();

            if (selects.Count == 0)
            {
                return query.Get
                (
                    mapper,
                    options.Filter.ToFilterExpression<TModel>(),
                    options.GetQueryableExpression(),
                    options.SelectExpand.GetIncludes().BuildIncludes<TModel>().ToArray()
                );
            }
            else
            {
                ParameterExpression param = Expression.Parameter(typeof(IQueryable<TModel>), "q");

                return query.Get
                (
                    mapper,
                    options.Filter.ToFilterExpression<TModel>(),
                    Expression.Lambda<Func<IQueryable<TModel>, IQueryable<object>>>
                    (
                        GetSelectMethodCall(options.GetOrderByMethod(param)), 
                        param
                    ),
                    options.SelectExpand.GetIncludes().BuildIncludes<TModel>().ToArray()
                );

                MethodCallExpression GetSelectMethodCall(MethodCallExpression orderBy)
                    => orderBy == null
                        ? param.GetSelectNew<TModel>(selects)
                        : orderBy.GetSelectNew<TModel>(selects);
            }
        }
```
`GetSelectNew()` is from `LogicBuilder.Expressions.Utils`.  Then add a separate Get method:

```c#
        public static ICollection<TModel> Get<TModel, TData>(this IQueryable<TData> query, IMapper mapper,
            Expression<Func<TModel, bool>> filter = null,
            Expression<Func<IQueryable<TModel>, IQueryable<object>>> queryFunc = null,
            IEnumerable<Expression<Func<TModel, object>>> includeProperties = null)
        {
            //Map the expressions
            Expression<Func<TData, bool>> f = mapper.MapExpression<Expression<Func<TData, bool>>>(filter);
            Func<IQueryable<TData>, IQueryable<object>> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, IQueryable<object>>>>(queryFunc).Compile();
            ICollection<Expression<Func<TData, object>>> includes = mapper.MapIncludesList<Expression<Func<TData, object>>>(includeProperties);

            if (filter != null)
                query = query.Where(f);

            if (includes != null)
                query = includes.Aggregate(query, (q, next) => q.Include(next));


            //Map and return the data
            return mapper.Map<IEnumerable<object>, IEnumerable<TModel>>
                (//mappedQueryFunc is never null for selects
                    mappedQueryFunc(query)
                        .ToList()
                        .Select(o => o.ToExpandoObject())
                ).ToList();
        }

        private static System.Dynamic.ExpandoObject ToExpandoObject(this object obj)
        {
            IDictionary<string, object> expando = new System.Dynamic.ExpandoObject();

            foreach (System.Reflection.PropertyInfo property in obj.GetType().GetProperties())
            {
                expando.Add(property.Name, property.GetValue(obj));
            }

            return (System.Dynamic.ExpandoObject)expando;
        }
```
This works at the top level e.g. `http://localhost:18664/opstenant?$top=5&$select=Name` **but** it gets more complicated with nested selects e.g. the following works with the current code (without narrowing the SQL query) `http://localhost:18664/opstenant?$top=5&$select=Name&$expand=Buildings($select=Name)` but not yet with this new approach.

**Comment by BlaiseD** [comment]
Fixed in [new repo](https://github.com/AutoMapper/AutoMapper.Extensions.OData).
