### ISSUE TITLE
Expand filtering without EF

### ISSUE THREAD

**Issue by ghost** [BlaiseD/LogicBuilder.OData#2]
Hi,
not sure if this might be the right place or [AutoMapper.Extensions.ExpressionMapping](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping). I'm not using Entity Framework but NHibernate and am trying to get $expand($filter=...) to work with expression mapping.
My request: `api/People?$expand=Trips($filter=contains(Name, '0') or Id eq '2')`
Repo with test code: [expandfilter](https://github.com/paulkroener/expandfilter)
Using `ProjectTo<>` works fine, but I need the expression mapping for more complex mapping cases. `UseAsDataSource` gives me an `ArgumentException` when the expand is applied by OData.

To get the expand itself to work without any filtering you can simply do:
```
var projection = query.UseAsDataSource(mapper).For<PersonRest>(null, membersToExpand);
options.ApplyTo(projection, AllowedQueryOptions.Expand);
```
This applies the options without the expand, but AutoMapper will still add the select expressions and the properties will still be expanded, but without any filtering, ordering etc.

So currently I'm wondering I could apply the expands to the query manually, as I cannot use the `Include()` extension as shown here: [query = includes.Aggregate(query, (q, next) => q.Include(next));](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/3#issuecomment-398549406).
My guess is to use an expression visitor using `UseAsDataSource().AfterProjection/BeforeProjection` to replace the expand expression AutoMapper produces. Any better ideas?
If this is solved I would apply the filter to that select expression. I already have a (rather ugly ATM) way of extracting the filter.

**Comment by BlaiseD** [comment]
Note that building include expressions is already different for [EF6](https://github.com/BlaiseD/LogicBuilder.OData/blob/abf3bed68e4a9121575e7b81b55e3d800c7abbd2/LogicBuilder.AspNetCore.OData/LinqExtensions.cs#L152) vs [EF Core](https://github.com/BlaiseD/LogicBuilder.DataComponents/blob/30808dec6889cb15c62ab5c29511c448c9b13915/LogicBuilder.Expressions.EntityFrameworkCore/QueryExtensions.cs#L31) .

[Even the underlying delegates are different](https://github.com/BlaiseD/LogicBuilder.OData/blob/abf3bed68e4a9121575e7b81b55e3d800c7abbd2/LogicBuilder.OData.EFCore/QueryableExtensions.cs#L132).

I would consider doing something similar for NHibernate -  I'm not familiar with include expressions for NHibernate but feel free to create a PR to add an NHibernate OData project here.
